sudo: required
services:
  - docker

before_install:
  - docker build -t carlodesutter/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run carlodesutter/docker-react-udemy npm run test -- --coverage